version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAIN: ${DOMAIN}
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./nginx/ssl:/etc/ssl
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/ssl:/etc/ssl
      - /var/www/certbot:/var/www/certbot
    entrypoint: [
      "certbot", "certonly", "--webroot",
      "--webroot-path=/var/www/certbot",
      "--email", "your-email@example.com",
      "--agree-tos", "--no-eff-email",
      "-d", "${DOMAIN}", "-d", "www.${DOMAIN}"
    ]
