name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      DOMAIN: ${{ secrets.DOMAIN }} # Переменная окружения для всего job
      ANOTHER_VAR: 'hello' # Использование секрета

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: echo $DOMAIN && echo $ANOTHER_VAR echo && whoami && pwd
